persistence true
persistence_location /mosquitto/data/
log_dest stdout

listener 1883
allow_anonymous false

listener 8883
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
allow_anonymous false

listener 9001
protocol websockets
allow_anonymous false

# Initialise this file before the first startup with mosquitto_ctrl dynsec init.
plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic-security.json
